### PR TITLE
Add an image tag names filter

### LINKED ISSUE #3781: Image tag name list is not filterable
### Expected behavior

Search image tag name in image card tag selection overlay

### Actual behavior

Tag names are not filterable and not sorted, user need to scroll to find the wanted tag name

### Steps to reproduce the behavior

  1. click on selecte tag overlay of an image card

### PR DESCRIPTION
**Pull request by Kribou**
Add an input text to filter tag names in image overlay. Fixes #3781 

Signed-off-by: Gael Hanquez <hanquez.gael@gmail.com>

### CODE REVIEW

**Comment by FrenchBen** [comment]
thanks @Kribou for the PR and enhancement - Can you add a screenshot/gif to the PR, so that we have a snapshot of what it's supposed to look like?

**Comment by Kribou** [comment]
Sure, I added an input field to be able to filter the tag name list instead of scrolling.

image

image

**Comment by FrenchBen** [comment]
Implementation looks good, but I'm seeing some odd shifts in the box layout - Is this something you could fix as part of this PR?
layout

You can see it in your filter as well, where the overlay box isn't 100% of the image box below it.

**Comment by Kribou** [comment]
Sure, I fixed it in the last commit.

image

**Pull request merged**
