### PR TITLE
Added small reset button for settings

### LINKED ISSUE #2633: Installing "portainer" on Windows 10
### Expected behavior

Container installs and runs.

### Actual behavior

Failed to install

### Information about the Issue

```
failed to register layer: re-exec error: exit status 1: output: remove \\?\C:\ProgramData\Docker\windowsfilter\ba67cbfae1e42e33934c654f4d15950069576ef3bdf7cb3b9cb57b8491387577\UtilityVM\Files\Windows\servicing\Packages\Microsoft-OneCore-Containers-Package~31bf3856ad364e35~amd64~~10.0.14393.0.cat: The process cannot access the file because it is being used by another process.
```

Docker is set to Windows container mode - other than that pretty much standard install.

### Steps to reproduce the behavior

Click install on portainer

### PR DESCRIPTION
**Pull request by FrenchBen**
This adds a small reset button that will allow a user to reset their local settings, should they run into issues. 
Fixes #2633

### CODE REVIEW

**Comment by brazitech** [comment]
still not working on windows 10.

**Comment by FrenchBen** [comment]
@brazitech Can you open an issue providing exact steps to replicate your problem?

**Comment by geoffroy-noel-ddh** [comment]
The reset button doesn't solve #2499 (on MacOS). I had to use the useVM = false in the console to make it work.

**Comment by alexxn** [comment]
Reset button is not working in Windows 10 + Docker Version 17.09.1-ce-win42 (14687) and Kitematic 0.17.2

**Pull request merged**
