### PR TITLE
Added hostname settings to container

### PR DESCRIPTION
**Pull request by daaru00**
According to https://github.com/docker/kitematic/issues/2350#issuecomment-287486749 I edited ports tab adding container's hostname configurations:
preview
If not set the current container hostname is loaded.

### CODE REVIEW

**Comment by daaru00** [comment]
It may be considered to add an input validation or an error handler.

**Comment by daaru00** [comment]
Something like this: https://github.com/daaru00/kitematic/commit/b8a40f77e7188ed53ace2e6af214b12534c851d6

hostname_not_valid

**Comment by FrenchBen** [comment]
@daaru00 that would be cool as well - If someone sets the wrong hostname, it'll break the current container and thus may help for inexperienced users.

**Comment by daaru00** [comment]
@FrenchBen exactly! Can you test the commit changes?

**Pull request merged**
