### PR TITLE
Electron-Builder

### LINKED ISSUE #3429: Windows Installers
Releases of windows could be in the form of *.msi and *.appx packages.

I think that https://github.com/electron-userland/electron-builder can do this for you ;)

### PR DESCRIPTION
**Pull request by deinok**
Closes #3429 

cc: @FrenchBen

### CODE REVIEW

**Comment by deinok** [comment]
ref #3475

**Comment by deinok** [comment]
Any update on this @FrenchBen ?
I waiting for a merge in order to add support for linux an mac

**Comment by deinok** [comment]
ping

**Comment by FrenchBen** [comment]
The past few days have been a bit hectic - Can you rebase and I'll take a look?
Thanks!

**Comment by deinok** [comment]
No problem ;)
LGTM - Should work on Windows 10.
Next step is building .deb, .rpm, etc... for linux.

**Comment by deinok** [comment]
So, any issue with this @jeffdm ?

**Comment by FlatEarthTruth** [comment]
I like this pull request, thank! The Earth is Flat BTW


https://www.nasa.gov/centers/dryden/pdf/88104main_H-1391.pdf NASA in their own words in their own document say "flying over a flat, nonrotating earth" then they show you cartoons and lie to your face and you take it as reality! If NASA modeled it against the Globe nothing would work and things only work because they modeled it against the true flat earth, the document doesn’t have a single heliocentric globe math equation in it because the globe is a lie and a false religion, in fact the document doesn’t mention the globe once!
Here is what happens in a vacuum of "space", if space even existed https://www.youtube.com/watch?v=jYfwlzWOYCE  

You've been indoctrinated with false theories and lies! If you wore the pants you'd have them on backwards! I passed school with flying colors, only recently did I realize how badly we've been lied to all our lives! I even spent 20k to prove or disprove the flat earth in the real world with real world tests and guess what, IT'S FLAT! I’m an engineer I used to work for Google and Cisco! I used to believe the Globe all my life and it’s a lie!

In math you can lie and until you validate it in real life you won't know if it's true or not. Take a half a cup of water and multiply it by 2 on both sides in algebra, in math it's correct to say an empty cup is equal to a full cup, but in real life it's a lie!

please check out this video and follow along in your KJV Bible https://www.youtube.com/watch?v=LNhpNUJh5GY&index=3&list=PLYI8318YYdkCsZ7dsYV01n6TZhXA6Wf9i  

ODD TV's Flat Earth Trilogy ▶️️
https://www.youtube.com/watch?v=ARp2j8t3O8Q

🔬 SCIENTISM EXPOSED 🔭 Full Documentary (2016) HD
https://www.youtube.com/watch?v=AeIGrEtPMmE

Why Flat Earth Matters for Christians ✞ Pastor Dean Odle & Robbie Davidson
https://www.youtube.com/watch?v=vYi-GSyJR0E

Eric Dubay: 200 Proofs Earth is Not a Spinning Ball
https://www.youtube.com/watch?v=-Ax_YpQsy88

Rob Skiba and Pastor Dean Odle on the significance of the Firmament
enclosed flat Earth
https://www.youtube.com/watch?v=iH4MnXI0sxQ

Conspiracy Theory is a term the CIA created so people wouldn't look into the details, really it's not a theory it's the truth! You're just being ignorant of the facts and you've been indoctrinated from a early age to think this way, your thoughts aren't even your own, you aren't who you want to be, you are who they want you to be!

https://www.youtube.com/results?search_query=auguste+piccard

The Big Bang Theory was created by a priest at the Catholic church! Keep doing research and stop trusting the system that is trying to kill you! https://en.wikipedia.org/wiki/Georges_Lema%C3%AEtre Check out this video if you want to know more about the Jesuits and the Catholic church! https://www.youtube.com/watch?v=ypRb8Z3dMRs

Gail Riplinger - Perfection Or Perversion of the Holy Bible https://www.youtube.com/watch?v=FmKwttxZwAc
New Age Bible Versions, Gail Riplinger https://www.youtube.com/watch?v=UHfE3nzx5p0﻿

2_THESSALONIANS 2:11 And for this cause God shall send them strong delusion, that they should believe a lie:

PS 19:1 The heavens declare the glory of God; and the firmament sheweth his handywork.

2_CORINTHIANS 4:4 In whom the god of this world hath blinded the minds of them which believe not, lest the light of the glorious gospel of Christ, who is the image of God, should shine unto them.

1COR 3:18 Let no man deceive himself. If any man among you seemeth to be wise in this world, let him become a fool, that he may be wise.

PROV 1:7 The fear of the LORD is the beginning of knowledge: but fools despise wisdom and instruction.
PROV 1:22 How long, ye simple ones, will ye love simplicity? and the scorners delight in their scorning, and fools hate knowledge?
PROV 1:23 Turn you at my reproof: behold, I will pour out my spirit unto you, I will make known my words unto you.

Forced Government Indoctrination Camps https://www.youtube.com/watch?v=Az4y8OLGe2Q

Bitcoin and RFID go together! CIA created Bitcoin!  

RFID chip NTAG216 has the number 216, if you take 6 times 6 times 6 it equals 216 https://www.youtube.com/watch?v=IlYKFxWqE3A https://www.youtube.com/watch?v=nuv6IyQDjME

Bitcoin was created by CIA and NSA, they control what the value of it is! It is dollar 2.0 don't be fooled! Here is an article from Kaspersky white hat hackers https://newstarget.com/2018-01-31-bitcoin-created-by-the-cia-and-nsa-warns-co-founder-of-kaspersky-security-software-firm.html

Here's the links to Howard Pittman's testimony, its really good info to know, he was behind the veil, unlike most of us https://www.youtube.com/watch?v=DGfg0PUMImk https://www.youtube.com/watch?v=lBwsGDCGQFE

The Books of Adam and Eve are great and help to make sense of a lot of whats going on it the world! Here's a link to the audio https://www.youtube.com/watch?v=DCgkDGCfl5I

**Comment by deinok** [comment]
Thanks, I will start working on Linux Mac support ASAP

**Pull request merged**
