### PR TITLE
Cmd + 0 to reopen closed window

### PR DESCRIPTION
**Pull request by mikaoelitiana**
This is a correction for issue #702

### CODE REVIEW

**Comment by FrenchBen** [comment]
Does this also work within Windows?

**Comment by FrenchBen** [comment]
LGTM @jeffdm PTAL

**Comment by mikaoelitiana** [comment]
I have not checked with windows yet but I think this will be ignored in windows as closing the screen will close the whole app

**Comment by mikaoelitiana** [comment]
I changed accelerator as suggested by @jeffdm

**Comment by FrenchBen** [comment]
@mikaoelitiana Could you squash your commits into 1 commit, since this is a simple change?
Once that's done, we'll be able to merge it

**Comment by mikaoelitiana** [comment]
I created another pull request with a single commit so I will close this one

**Pull request closed without merging**
