### PR TITLE
Fix #702

### LINKED ISSUE #702: Cmd + 0 should re-open Window
If I close the Kitematic window using Cmd-W, there's no way to re-open the window without quitting Kitematic and restarting it. Combined with the option to shutdown the Linux VM on closing Kitematic, this is problematic.

### PR DESCRIPTION
**Pull request by mikaoelitiana**
Changes to fix #702 in a single commit

### CODE REVIEW

**Comment by jeffdm** [comment]
LGTM

Before merge, can you squash the commits with `git rebase -i` and then sign your commit?

```
$ git commit --amend -s --no-edit
$ git push -f
```

**Comment by mikaoelitiana** [comment]
Done!

**Comment by jeffdm** [comment]
Thanks!

**Comment by jeffdm** [comment]
Thanks so much for the PR!

**Comment by mikaoelitiana** [comment]
You are welcome. I am please to contribute.

**Pull request merged**
