### PR TITLE
Use which to find docker-machine

### PR DESCRIPTION
**Pull request by StefanScherer**
I started to build a [Chocolatey package for Kitematic](https://github.com/stefanScherer/choco-kitematic). But installing VirtualBox, docker-machine and then Kitematic through `choco install` doesn't work yet.

The problem is that Kitematic searches the `docker-machine` binary only with the environment variable `DOCKER_TOOLBOX_INSTALL_PATH`. After installing `docker-machine` with `choco install docker-machine` it is in the user's PATH.

So I enhanced the check to find `docker-machine` in the PATH if no such environment variable is set. The environment variable still has priority over the PATH to keep the same behaviour using the Docker Toolbox.

For Linux the `docker-machine` binary also is searched in PATH so it could be put to another place (perhaps someone compiles it from Go sources).

### CODE REVIEW

**Comment by FrenchBen** [comment]
Although I'm a big fan of Chocolatey, we use the Docker Toolbox to do the install on Windows and set the above variables. 
Similarly on the Mac, we use the Docker Toolbox to do the install instead of pushing for a `brew` solution. 

With that said, I do like the improvements to the code in order to locate the proper binary - I'll QA the changes and see if there is a 'breaking' condition. 

As another side note, while you're in there, can you also update the call to the `existSync`? See:
https://nodejs.org/api/fs.html#fs_fs_existssync_path

**Comment by xslim** [comment]
I vote to include this PR. On Mac, I install docker via Homebrew. And it installs `docker-machine` in the Homebrew path...

**Comment by FrenchBen** [comment]
@jeffdm PTAL

**Comment by StefanScherer** [comment]
Any updates? In the meantime someone else has started a Chocolatey package https://chocolatey.org/packages/docker-kitematic and I showed him this PR.

**Comment by FrenchBen** [comment]
@StefanScherer I'm gona go ahead and merge this as it seems to be working well  - Sorry for the delay

**Comment by StefanScherer** [comment]
Thanks @FrenchBen - no problem ;-)

**Pull request merged**
