### PR TITLE
#1041 Add feature to find text in log

### PR DESCRIPTION
**Pull request by ysm001**
This PR adds a new feature allowing users to find text in log.

kitematic-search

- Open search panel: Ctrl (or Cmd) + F
- Find next: Enter
- Find previous: Shift + Enter
- Close search panel: Esc

### CODE REVIEW

**Comment by FrenchBen** [comment]
I have a container that's just a redis DB that was shutdown for a while and thus didn't have any logs - This caused the following error: 
`ContainerHomeLogs.react.js:55 Uncaught TypeError: Cannot read property 'length' of undefined` 

The above error prevented me from doing anything but close the app. 
Could you see why this is happening?

**Comment by FrenchBen** [comment]
@ysm001 ping

**Comment by FrenchBen** [comment]
LGTM

**Comment by ClemMakesApps** [comment]
The search is currently case sensitive. Shouldn't it be other way around?

**Comment by FrenchBen** [comment]
Closing in favor of #1728

**Comment by shinriyo** [comment]
I want this feature

**Pull request closed without merging**
