### PR TITLE
fix: replace custom window buttons with native

### LINKED ISSUE #1816: Option-Click on Mac Should Maximize
### Expected behavior
Option-clicking on the green button in the title bar should cause the window to maximize without going fullscreen.

### Actual behavior
The window goes into fullscreen mode.

### Steps to reproduce the behavior

  1. Option-click on the green button in the titlebar.

### PR DESCRIPTION
**Pull request by mikaoelitiana**
fixes #1816

### CODE REVIEW

**Comment by FrenchBen** [comment]
Do you think you can fix the layout for windows, so that it's consistent with Linux+OSX. 
Login button on the left, kitematic logo on the right?
Like:

**Comment by FrenchBen** [comment]
@mikaoelitiana In case you missed it, there were some nice enhancements here as well: https://github.com/docker/kitematic/pull/1559

**Comment by mikaoelitiana** [comment]
Oh that's great!! I think they have done good job in this mentionned PR so maybe we can close this one

**Comment by mikaoelitiana** [comment]
I will check the layout in Windows and PR if any change needed there.

**Comment by FrenchBen** [comment]
A couple of things weren't smooth in the mentioned PR and unfortunately the original dev wasn't able to finish it :(

**Comment by mikaoelitiana** [comment]
I have some trouble testing this in Windows as I have no Windows computer and tried to launch it in a VM. Docker won't be installed in the VM as Windows test VMs don't have 64bit version. 
Can someone check this out for me in Windows?

**Comment by FrenchBen** [comment]
I'll give it a shot - thanks for the help

**Comment by Bigguy34** [comment]
Whoa... Does this PR get rid of the frameless option? Sorry @FrenchBen changing jobs, and buying a new house really cuts down on my free time. If we are going to get rid of that electron config option everywhere(Linux, OSX, Windows) my original PR will work really well, and it is much easier. I think for now this will be an easier direction than trying to implement a native looking menu in React. I can get my original PR up to speed if need be.

**Comment by FrenchBen** [comment]
@Bigguy34 It may be a lot easier to do so - the original intent was to keep a similar look and feel across all OS, but seems to add some un-needed overhead. WDYT?

**Comment by Bigguy34** [comment]
Yea so in my PR I had it optionally switching between frame:true and frame:false depending on whether or not a user was in windows or mac. In this PR we just set frame:true everywhere, and just handle the position of elements in the topbar based on whether or not we are in windows. I do think the work I did around the menu would definitely still apply. Originally I was going to try and remake all the "native" looking controls in React, [At a high level something like this](http://stackoverflow.com/questions/35876939/frameless-window-with-controls-in-electron-windows). If your ok with it we add the frame back in everywhere, we will just have to work a little harder to make it look pretty in windows. WDYT @FrenchBen I am working on getting my branch up to date, and I think I will finally have time to finish my PR. I am really sorry it to so long. What are your thoughts @mikaoelitiana ?

**Comment by mikaoelitiana** [comment]
@Bigguy34 I am OK with the idea to continue your PR which is already quite advanced and close this one

**Comment by FrenchBen** [comment]
Closing in favor of @Bigguy34's PR #1559

**Pull request closed without merging**
