### PR TITLE
Fixes #1061 with VM name selection

### LINKED ISSUE #1061: Feature request - Change VM name ( " default " )
Please allow to select name for the VM that Kitematic uses for dockers, and allow to rename the existent VM.

### PR DESCRIPTION
**Pull request by FrenchBen**
Signed-off-by: French Ben <me+git@frenchben.com>

### CODE REVIEW

**Comment by FrenchBen** [comment]
Tried to QA with Windows but currently getting some errors from virtualbox. Will wait for new toolbox to be pushed out

**Comment by jeffdm** [comment]
Taking a look!

**Comment by FrenchBen** [comment]
FYI, it looks like the branch needs to be updated prior to final push

**Comment by pmario** [comment]
@FrenchBen Did this PR quietly die?

**Comment by FrenchBen** [comment]
@pmario it did due to machine management. The VM selection was fine, but for the most part, there was no mounting of folders and misc actions were broken.

**Comment by pmario** [comment]
Yea. I found out already, that the whole system is heavily connected to vbox. From a programmers point of view. Way to heavy. ...

IMO kitematic needs a plugin mechanism, where vbox handling is a plugin too. 

This would give us (the community with different requirements) the possibility to remove the vbox battery and replace it. 

At the moment I'm investigating to create shared folders with hyper-v and using container tech and not vbox tech.

**Comment by FrenchBen** [comment]
I agree with that approach, unfortunately the current heavy vbox integration makes it difficult. 
We've considered re-writing the app completely with the  plugin in mind, but there's a lot to do to make that happen. 
I'm open to suggestions if you see an easy way to get that working?

**Pull request closed without merging**
