### PR TITLE
Docs validation checker fixes

### PR DESCRIPTION
**Pull request by SvenDowideit**
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>

please :)

### CODE REVIEW

**Comment by SvenDowideit** [comment]
oh :( jenkins is mega busy atm.

**Comment by SvenDowideit** [comment]
@jeffdm @moxiegirl we have docs checkers on PRs here too now, please ping me if you see something odd happening

**Comment by jeffdm** [comment]
LGTM

**Comment by FrenchBen** [comment]
:+1:

**Pull request merged**
