### PR TITLE
3223 Font too small and can't copy log.

### PR DESCRIPTION
**Pull request by collin5**
**What does this PR do?**

- Adds button for the user to copy container logs to the clipboard.
- Enables user to adjust the font size for logs.

[Fixes issue #3223 ]

screen shot 2017-11-29 at 12 01 13

### CODE REVIEW

**Comment by collin5** [comment]
#3369

**Comment by FrenchBen** [comment]
Thanks @collin5 for adding this - Could you remove the "box" around the buttons, so that they integrated better?

**Comment by collin5** [comment]
@FrenchBen Thanks for your feedback, this should be fixed now 👍

**Comment by FrenchBen** [comment]
Thanks @collin5 one more change before merge - Could we get the "Copied!" text to be white instead of Green? The green doesn't seem to fit with the overall theme

**Comment by collin5** [comment]
Awesome 👍, let me do that ASAP

**Comment by collin5** [comment]
@FrenchBen  Done 👍 . Thanks :)

**Pull request merged**
