### PR TITLE
added toolbox overview

### PR DESCRIPTION
**Pull request by londoncalling**
Signed-off-by: Victoria Bialas <victoria.bialas@docker.com>

### CODE REVIEW

**Comment by jeffdm** [comment]
LGTM, after CI :smiley:

**Comment by londoncalling** [comment]
@SvenDowideit @moxiegirl I've added a succinct Toolbox overview and it's sitting properly in the menus. Let me know if it's good to go :-)

**Comment by londoncalling** [comment]
not sure what's going on with the build failure

**Comment by londoncalling** [comment]
@moxiegirl @SvenDowideit @jeffdm pushed two additional changes for keywords and menu weight in metadata. Let me know if this is good to go. I'm done with it on my end.

**Comment by mchiang0610** [comment]
LGTM. @londoncalling

**Comment by jeffdm** [comment]
LGTM

**Pull request merged**
